#define PRODUCT_VERSION_MAJOR    1
#define PRODUCT_VERSION_MINOR    0
#define PRODUCT_VERSION_PATCH    0
#define PRODUCT_VERSION_BUILD    27326
#define PRODUCT_VERSION_REVISION 185837

#define FILE_VERSION_RESOURCE     1,0,0,27326
#define PRODUCT_VERSION_RESOURCE  1,0,0,27326

#define FILE_VERSION_RESOURCE_STR    "1.0.0.27326\0"
#define PRODUCT_VERSION_RESOURCE_STR "1.0.0.27326\0"
#define BUILD_REVISION_STRING        "Build 27326 Rev. 185837"

#define PRODUCT_COMMENTS           "\0"
#define PRODUCT_COMPANY_NAME       "8ATHALA Co., Ltd.\0"
#define PRODUCT_COMPANY_COPYRIGHT  "Copyright (C) 2026\0"
#define PRODUCT_FILE_DESCRIPTION   "Module Extension\0"
#define PRODUCT_INTERNAL_NAME      "HYDRA\0"
#define PRODUCT_ORIGINAL_FILENAME  "HYDRA.DLL\0"
#define PRODUCT_BUNDLE             "HydraFramework Module Helper\0"
