#define PRODUCT_VERSION_MAJOR    1
#define PRODUCT_VERSION_MINOR    0
#define PRODUCT_VERSION_PATCH    0
#define PRODUCT_VERSION_BUILD    28326
#define PRODUCT_VERSION_REVISION 042158

#define FILE_VERSION_RESOURCE     1,0,0,28326
#define PRODUCT_VERSION_RESOURCE  1,0,0,28326

#define FILE_VERSION_RESOURCE_STR    "1.0.0.28326\0"
#define PRODUCT_VERSION_RESOURCE_STR "1.0.0.28326\0"
#define BUILD_REVISION_STRING        "Build 28326 Rev. 042158"

#define PRODUCT_COMMENTS           "\0"
#define PRODUCT_COMPANY_NAME       "8ATHALA Co., Ltd.\0"
#define PRODUCT_COMPANY_COPYRIGHT  "Copyright (C) 2026\0"
#define PRODUCT_FILE_DESCRIPTION   "HydraFramework Module\0"
#define PRODUCT_INTERNAL_NAME      "HYDRA\0"
#define PRODUCT_ORIGINAL_FILENAME  "HYDRA.DLL\0"
#define PRODUCT_BUNDLE             "HydraFramework Module\0"
